# Generated by Django 5.0.4 on 2024-10-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0011_listadeseos'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elegant_touch_app.producto'),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='fecha_reseña',
            field=models.DateField(auto_now_add=True),
        ),
    ]
