# Generated by Django 5.0.4 on 2024-10-21 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0012_reseña_producto_alter_reseña_fecha_reseña'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseña',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='comentario_reseña',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='fecha_reseña',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='puntuacion_reseña',
        ),
        migrations.AddField(
            model_name='reseña',
            name='calificacion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reseña',
            name='contenido',
            field=models.TextField(default='Sin contenido'),
        ),
        migrations.AddField(
            model_name='reseña',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=255),
        ),
        migrations.AddField(
            model_name='reseña',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
