# Generated by Django 5.0.4 on 2024-10-22 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0013_remove_reseña_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='calificacion',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
