# Generated by Django 5.0.4 on 2024-11-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0018_perfilusuario_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='elegant_touch_app.marca'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='apellido_proveedor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo_proveedor',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_proveedor',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
