# Generated by Django 5.0.4 on 2024-11-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0021_alter_inventario_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='agotado',
            field=models.BooleanField(default=False),
        ),
    ]
