# Generated by Django 5.0.7 on 2024-08-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='correo_cliente',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
    ]
