# Generated by Django 5.0.4 on 2024-10-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0009_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_producto',
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/imagenes/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='elegant_touch_app.producto')),
            ],
        ),
    ]
