# Generated by Django 5.0.4 on 2024-10-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0015_alter_contacto_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
