# Generated by Django 5.0.4 on 2024-10-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0016_imagenproducto_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
