# Generated by Django 5.0.4 on 2024-10-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0017_perfilusuario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
