# Generated by Django 5.0.4 on 2024-11-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0020_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='elegant_touch_app.proveedor'),
        ),
    ]
