# Generated by Django 5.0.4 on 2024-11-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0023_alter_inventario_cantidad_maxima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metododepago',
            name='nombre_metodo_pago',
            field=models.CharField(choices=[('Bancolombia', 'Bancolombia'), ('Nequi', 'Nequi')], max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='guia_pedido',
            field=models.CharField(max_length=100),
        ),
    ]
