# Generated by Django 5.0.7 on 2024-11-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0026_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
