# Generated by Django 5.0.7 on 2024-11-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0030_rename_fecha_creacion_pedidocliente_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoAdministrador',
        ),
    ]
