# Generated by Django 5.0.4 on 2024-12-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0031_delete_pedidoadministrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoCliente',
        ),
    ]
