# Generated by Django 5.0.4 on 2024-12-01 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0033_pedidocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='elegant_touch_app.pedidocliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elegant_touch_app.producto')),
            ],
        ),
    ]
