# Generated by Django 5.0.4 on 2024-12-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0034_pedidoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
