# Generated by Django 5.0.4 on 2024-12-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0036_pedidocliente_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='total',
            new_name='item_total',
        ),
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='cantidad',
            new_name='quantity',
        ),
    ]
