# Generated by Django 5.0.4 on 2024-12-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0037_rename_total_pedidoitem_item_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocliente',
            name='total',
        ),
    ]
