# Generated by Django 5.0.4 on 2024-12-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elegant_touch_app', '0040_alter_pedidocliente_options_pedidocliente_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
